//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bogazici_service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Satir", Namespace="http://service.bogazici.com.tr/")]
    public partial class Satir : object
    {
        
        private string StokKodField;
        
        private string SatirAciklamaField;
        
        private int AdetField;
        
        private double DovizFiyatField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StokKod
        {
            get
            {
                return this.StokKodField;
            }
            set
            {
                this.StokKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SatirAciklama
        {
            get
            {
                return this.SatirAciklamaField;
            }
            set
            {
                this.SatirAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Adet
        {
            get
            {
                return this.AdetField;
            }
            set
            {
                this.AdetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double DovizFiyat
        {
            get
            {
                return this.DovizFiyatField;
            }
            set
            {
                this.DovizFiyatField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Donus", Namespace="http://service.bogazici.com.tr/")]
    public partial class Donus : object
    {
        
        private int SonucField;
        
        private string SiparisNoField;
        
        private string HataAciklamaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sonuc
        {
            get
            {
                return this.SonucField;
            }
            set
            {
                this.SonucField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SiparisNo
        {
            get
            {
                return this.SiparisNoField;
            }
            set
            {
                this.SiparisNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataAciklama
        {
            get
            {
                return this.HataAciklamaField;
            }
            set
            {
                this.HataAciklamaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bogazici.com.tr/", ConfigurationName="bogazici_service.BBXMLServicesSoap")]
    public interface BBXMLServicesSoap
    {
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProducts", ReplyAction="*")]
        bogazici_service.GetProductsResponse GetProducts(bogazici_service.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetProductsResponse> GetProductsAsync(bogazici_service.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProductDimensions", ReplyAction="*")]
        bogazici_service.GetProductDimensionsResponse GetProductDimensions(bogazici_service.GetProductDimensionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProductDimensions", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetProductDimensionsResponse> GetProductDimensionsAsync(bogazici_service.GetProductDimensionsRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProductDetails", ReplyAction="*")]
        bogazici_service.GetProductDetailsResponse GetProductDetails(bogazici_service.GetProductDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetProductDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetProductDetailsResponse> GetProductDetailsAsync(bogazici_service.GetProductDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetPriceANDStock", ReplyAction="*")]
        bogazici_service.GetPriceANDStockResponse GetPriceANDStock(bogazici_service.GetPriceANDStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetPriceANDStock", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetPriceANDStockResponse> GetPriceANDStockAsync(bogazici_service.GetPriceANDStockRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetShipInfo", ReplyAction="*")]
        bogazici_service.GetShipInfoResponse GetShipInfo(bogazici_service.GetShipInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetShipInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetShipInfoResponse> GetShipInfoAsync(bogazici_service.GetShipInfoRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetOrderItemList", ReplyAction="*")]
        bogazici_service.GetOrderItemListResponse GetOrderItemList(bogazici_service.GetOrderItemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/GetOrderItemList", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.GetOrderItemListResponse> GetOrderItemListAsync(bogazici_service.GetOrderItemListRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/TPLinkSatis", ReplyAction="*")]
        bogazici_service.TPLinkSatisResponse TPLinkSatis(bogazici_service.TPLinkSatisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/TPLinkSatis", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.TPLinkSatisResponse> TPLinkSatisAsync(bogazici_service.TPLinkSatisRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/TPLinkStok", ReplyAction="*")]
        bogazici_service.TPLinkStokResponse TPLinkStok(bogazici_service.TPLinkStokRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/TPLinkStok", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.TPLinkStokResponse> TPLinkStokAsync(bogazici_service.TPLinkStokRequest request);
        
        // CODEGEN: Generating message contract since element name BayiKodu from namespace http://service.bogazici.com.tr/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/CreateOrder", ReplyAction="*")]
        bogazici_service.CreateOrderResponse CreateOrder(bogazici_service.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bogazici.com.tr/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bogazici_service.CreateOrderResponse> CreateOrderAsync(bogazici_service.CreateOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductsRequestBody Body;
        
        public GetProductsRequest()
        {
        }
        
        public GetProductsRequest(bogazici_service.GetProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetProductsRequestBody()
        {
        }
        
        public GetProductsRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductsResponseBody Body;
        
        public GetProductsResponse()
        {
        }
        
        public GetProductsResponse(bogazici_service.GetProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetProductsResult;
        
        public GetProductsResponseBody()
        {
        }
        
        public GetProductsResponseBody(System.Xml.XmlElement GetProductsResult)
        {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDimensionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDimensions", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductDimensionsRequestBody Body;
        
        public GetProductDimensionsRequest()
        {
        }
        
        public GetProductDimensionsRequest(bogazici_service.GetProductDimensionsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductDimensionsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetProductDimensionsRequestBody()
        {
        }
        
        public GetProductDimensionsRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDimensionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDimensionsResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductDimensionsResponseBody Body;
        
        public GetProductDimensionsResponse()
        {
        }
        
        public GetProductDimensionsResponse(bogazici_service.GetProductDimensionsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductDimensionsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetProductDimensionsResult;
        
        public GetProductDimensionsResponseBody()
        {
        }
        
        public GetProductDimensionsResponseBody(System.Xml.XmlElement GetProductDimensionsResult)
        {
            this.GetProductDimensionsResult = GetProductDimensionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDetailsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDetails", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductDetailsRequestBody Body;
        
        public GetProductDetailsRequest()
        {
        }
        
        public GetProductDetailsRequest(bogazici_service.GetProductDetailsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductDetailsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetProductDetailsRequestBody()
        {
        }
        
        public GetProductDetailsRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductDetailsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductDetailsResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetProductDetailsResponseBody Body;
        
        public GetProductDetailsResponse()
        {
        }
        
        public GetProductDetailsResponse(bogazici_service.GetProductDetailsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetProductDetailsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetProductDetailsResult;
        
        public GetProductDetailsResponseBody()
        {
        }
        
        public GetProductDetailsResponseBody(System.Xml.XmlElement GetProductDetailsResult)
        {
            this.GetProductDetailsResult = GetProductDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceANDStockRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceANDStock", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetPriceANDStockRequestBody Body;
        
        public GetPriceANDStockRequest()
        {
        }
        
        public GetPriceANDStockRequest(bogazici_service.GetPriceANDStockRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetPriceANDStockRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetPriceANDStockRequestBody()
        {
        }
        
        public GetPriceANDStockRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPriceANDStockResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPriceANDStockResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetPriceANDStockResponseBody Body;
        
        public GetPriceANDStockResponse()
        {
        }
        
        public GetPriceANDStockResponse(bogazici_service.GetPriceANDStockResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetPriceANDStockResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetPriceANDStockResult;
        
        public GetPriceANDStockResponseBody()
        {
        }
        
        public GetPriceANDStockResponseBody(System.Xml.XmlElement GetPriceANDStockResult)
        {
            this.GetPriceANDStockResult = GetPriceANDStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipInfo", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetShipInfoRequestBody Body;
        
        public GetShipInfoRequest()
        {
        }
        
        public GetShipInfoRequest(bogazici_service.GetShipInfoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetShipInfoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetShipInfoRequestBody()
        {
        }
        
        public GetShipInfoRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShipInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShipInfoResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetShipInfoResponseBody Body;
        
        public GetShipInfoResponse()
        {
        }
        
        public GetShipInfoResponse(bogazici_service.GetShipInfoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetShipInfoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetShipInfoResult;
        
        public GetShipInfoResponseBody()
        {
        }
        
        public GetShipInfoResponseBody(System.Xml.XmlElement GetShipInfoResult)
        {
            this.GetShipInfoResult = GetShipInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderItemListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderItemList", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetOrderItemListRequestBody Body;
        
        public GetOrderItemListRequest()
        {
        }
        
        public GetOrderItemListRequest(bogazici_service.GetOrderItemListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetOrderItemListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public GetOrderItemListRequestBody()
        {
        }
        
        public GetOrderItemListRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderItemListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderItemListResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.GetOrderItemListResponseBody Body;
        
        public GetOrderItemListResponse()
        {
        }
        
        public GetOrderItemListResponse(bogazici_service.GetOrderItemListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class GetOrderItemListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement GetOrderItemListResult;
        
        public GetOrderItemListResponseBody()
        {
        }
        
        public GetOrderItemListResponseBody(System.Xml.XmlElement GetOrderItemListResult)
        {
            this.GetOrderItemListResult = GetOrderItemListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPLinkSatisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TPLinkSatis", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.TPLinkSatisRequestBody Body;
        
        public TPLinkSatisRequest()
        {
        }
        
        public TPLinkSatisRequest(bogazici_service.TPLinkSatisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class TPLinkSatisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public TPLinkSatisRequestBody()
        {
        }
        
        public TPLinkSatisRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPLinkSatisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TPLinkSatisResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.TPLinkSatisResponseBody Body;
        
        public TPLinkSatisResponse()
        {
        }
        
        public TPLinkSatisResponse(bogazici_service.TPLinkSatisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class TPLinkSatisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement TPLinkSatisResult;
        
        public TPLinkSatisResponseBody()
        {
        }
        
        public TPLinkSatisResponseBody(System.Xml.XmlElement TPLinkSatisResult)
        {
            this.TPLinkSatisResult = TPLinkSatisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPLinkStokRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TPLinkStok", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.TPLinkStokRequestBody Body;
        
        public TPLinkStokRequest()
        {
        }
        
        public TPLinkStokRequest(bogazici_service.TPLinkStokRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class TPLinkStokRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        public TPLinkStokRequestBody()
        {
        }
        
        public TPLinkStokRequestBody(string BayiKodu, string EPosta, string Sifre)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TPLinkStokResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TPLinkStokResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.TPLinkStokResponseBody Body;
        
        public TPLinkStokResponse()
        {
        }
        
        public TPLinkStokResponse(bogazici_service.TPLinkStokResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class TPLinkStokResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Xml.XmlElement TPLinkStokResult;
        
        public TPLinkStokResponseBody()
        {
        }
        
        public TPLinkStokResponseBody(System.Xml.XmlElement TPLinkStokResult)
        {
            this.TPLinkStokResult = TPLinkStokResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrder", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.CreateOrderRequestBody Body;
        
        public CreateOrderRequest()
        {
        }
        
        public CreateOrderRequest(bogazici_service.CreateOrderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class CreateOrderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BayiKodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPosta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriSiparisNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SiparisAciklama;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SevkiyatKod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bogazici_service.Satir[] Satirs;
        
        public CreateOrderRequestBody()
        {
        }
        
        public CreateOrderRequestBody(string BayiKodu, string EPosta, string Sifre, string MusteriSiparisNo, string SiparisAciklama, string SevkiyatKod, bogazici_service.Satir[] Satirs)
        {
            this.BayiKodu = BayiKodu;
            this.EPosta = EPosta;
            this.Sifre = Sifre;
            this.MusteriSiparisNo = MusteriSiparisNo;
            this.SiparisAciklama = SiparisAciklama;
            this.SevkiyatKod = SevkiyatKod;
            this.Satirs = Satirs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderResponse", Namespace="http://service.bogazici.com.tr/")]
        public bogazici_service.CreateOrderResponseBody Body;
        
        public CreateOrderResponse()
        {
        }
        
        public CreateOrderResponse(bogazici_service.CreateOrderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://service.bogazici.com.tr/")]
    public partial class CreateOrderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bogazici_service.Donus CreateOrderResult;
        
        public CreateOrderResponseBody()
        {
        }
        
        public CreateOrderResponseBody(bogazici_service.Donus CreateOrderResult)
        {
            this.CreateOrderResult = CreateOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface BBXMLServicesSoapChannel : bogazici_service.BBXMLServicesSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class BBXMLServicesSoapClient : System.ServiceModel.ClientBase<bogazici_service.BBXMLServicesSoap>, bogazici_service.BBXMLServicesSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BBXMLServicesSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BBXMLServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), BBXMLServicesSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BBXMLServicesSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BBXMLServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BBXMLServicesSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BBXMLServicesSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BBXMLServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetProductsResponse bogazici_service.BBXMLServicesSoap.GetProducts(bogazici_service.GetProductsRequest request)
        {
            return base.Channel.GetProducts(request);
        }
        
        public System.Xml.XmlElement GetProducts(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductsRequest inValue = new bogazici_service.GetProductsRequest();
            inValue.Body = new bogazici_service.GetProductsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetProductsResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetProductsResponse> bogazici_service.BBXMLServicesSoap.GetProductsAsync(bogazici_service.GetProductsRequest request)
        {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetProductsResponse> GetProductsAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductsRequest inValue = new bogazici_service.GetProductsRequest();
            inValue.Body = new bogazici_service.GetProductsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetProductDimensionsResponse bogazici_service.BBXMLServicesSoap.GetProductDimensions(bogazici_service.GetProductDimensionsRequest request)
        {
            return base.Channel.GetProductDimensions(request);
        }
        
        public System.Xml.XmlElement GetProductDimensions(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductDimensionsRequest inValue = new bogazici_service.GetProductDimensionsRequest();
            inValue.Body = new bogazici_service.GetProductDimensionsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetProductDimensionsResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetProductDimensions(inValue);
            return retVal.Body.GetProductDimensionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetProductDimensionsResponse> bogazici_service.BBXMLServicesSoap.GetProductDimensionsAsync(bogazici_service.GetProductDimensionsRequest request)
        {
            return base.Channel.GetProductDimensionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetProductDimensionsResponse> GetProductDimensionsAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductDimensionsRequest inValue = new bogazici_service.GetProductDimensionsRequest();
            inValue.Body = new bogazici_service.GetProductDimensionsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetProductDimensionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetProductDetailsResponse bogazici_service.BBXMLServicesSoap.GetProductDetails(bogazici_service.GetProductDetailsRequest request)
        {
            return base.Channel.GetProductDetails(request);
        }
        
        public System.Xml.XmlElement GetProductDetails(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductDetailsRequest inValue = new bogazici_service.GetProductDetailsRequest();
            inValue.Body = new bogazici_service.GetProductDetailsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetProductDetailsResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetProductDetails(inValue);
            return retVal.Body.GetProductDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetProductDetailsResponse> bogazici_service.BBXMLServicesSoap.GetProductDetailsAsync(bogazici_service.GetProductDetailsRequest request)
        {
            return base.Channel.GetProductDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetProductDetailsResponse> GetProductDetailsAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetProductDetailsRequest inValue = new bogazici_service.GetProductDetailsRequest();
            inValue.Body = new bogazici_service.GetProductDetailsRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetProductDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetPriceANDStockResponse bogazici_service.BBXMLServicesSoap.GetPriceANDStock(bogazici_service.GetPriceANDStockRequest request)
        {
            return base.Channel.GetPriceANDStock(request);
        }
        
        public System.Xml.XmlElement GetPriceANDStock(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetPriceANDStockRequest inValue = new bogazici_service.GetPriceANDStockRequest();
            inValue.Body = new bogazici_service.GetPriceANDStockRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetPriceANDStockResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetPriceANDStock(inValue);
            return retVal.Body.GetPriceANDStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetPriceANDStockResponse> bogazici_service.BBXMLServicesSoap.GetPriceANDStockAsync(bogazici_service.GetPriceANDStockRequest request)
        {
            return base.Channel.GetPriceANDStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetPriceANDStockResponse> GetPriceANDStockAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetPriceANDStockRequest inValue = new bogazici_service.GetPriceANDStockRequest();
            inValue.Body = new bogazici_service.GetPriceANDStockRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetPriceANDStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetShipInfoResponse bogazici_service.BBXMLServicesSoap.GetShipInfo(bogazici_service.GetShipInfoRequest request)
        {
            return base.Channel.GetShipInfo(request);
        }
        
        public System.Xml.XmlElement GetShipInfo(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetShipInfoRequest inValue = new bogazici_service.GetShipInfoRequest();
            inValue.Body = new bogazici_service.GetShipInfoRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetShipInfoResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetShipInfo(inValue);
            return retVal.Body.GetShipInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetShipInfoResponse> bogazici_service.BBXMLServicesSoap.GetShipInfoAsync(bogazici_service.GetShipInfoRequest request)
        {
            return base.Channel.GetShipInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetShipInfoResponse> GetShipInfoAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetShipInfoRequest inValue = new bogazici_service.GetShipInfoRequest();
            inValue.Body = new bogazici_service.GetShipInfoRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetShipInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.GetOrderItemListResponse bogazici_service.BBXMLServicesSoap.GetOrderItemList(bogazici_service.GetOrderItemListRequest request)
        {
            return base.Channel.GetOrderItemList(request);
        }
        
        public System.Xml.XmlElement GetOrderItemList(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetOrderItemListRequest inValue = new bogazici_service.GetOrderItemListRequest();
            inValue.Body = new bogazici_service.GetOrderItemListRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.GetOrderItemListResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).GetOrderItemList(inValue);
            return retVal.Body.GetOrderItemListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.GetOrderItemListResponse> bogazici_service.BBXMLServicesSoap.GetOrderItemListAsync(bogazici_service.GetOrderItemListRequest request)
        {
            return base.Channel.GetOrderItemListAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.GetOrderItemListResponse> GetOrderItemListAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.GetOrderItemListRequest inValue = new bogazici_service.GetOrderItemListRequest();
            inValue.Body = new bogazici_service.GetOrderItemListRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).GetOrderItemListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.TPLinkSatisResponse bogazici_service.BBXMLServicesSoap.TPLinkSatis(bogazici_service.TPLinkSatisRequest request)
        {
            return base.Channel.TPLinkSatis(request);
        }
        
        public System.Xml.XmlElement TPLinkSatis(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.TPLinkSatisRequest inValue = new bogazici_service.TPLinkSatisRequest();
            inValue.Body = new bogazici_service.TPLinkSatisRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.TPLinkSatisResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).TPLinkSatis(inValue);
            return retVal.Body.TPLinkSatisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.TPLinkSatisResponse> bogazici_service.BBXMLServicesSoap.TPLinkSatisAsync(bogazici_service.TPLinkSatisRequest request)
        {
            return base.Channel.TPLinkSatisAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.TPLinkSatisResponse> TPLinkSatisAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.TPLinkSatisRequest inValue = new bogazici_service.TPLinkSatisRequest();
            inValue.Body = new bogazici_service.TPLinkSatisRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).TPLinkSatisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.TPLinkStokResponse bogazici_service.BBXMLServicesSoap.TPLinkStok(bogazici_service.TPLinkStokRequest request)
        {
            return base.Channel.TPLinkStok(request);
        }
        
        public System.Xml.XmlElement TPLinkStok(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.TPLinkStokRequest inValue = new bogazici_service.TPLinkStokRequest();
            inValue.Body = new bogazici_service.TPLinkStokRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            bogazici_service.TPLinkStokResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).TPLinkStok(inValue);
            return retVal.Body.TPLinkStokResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.TPLinkStokResponse> bogazici_service.BBXMLServicesSoap.TPLinkStokAsync(bogazici_service.TPLinkStokRequest request)
        {
            return base.Channel.TPLinkStokAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.TPLinkStokResponse> TPLinkStokAsync(string BayiKodu, string EPosta, string Sifre)
        {
            bogazici_service.TPLinkStokRequest inValue = new bogazici_service.TPLinkStokRequest();
            inValue.Body = new bogazici_service.TPLinkStokRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            return ((bogazici_service.BBXMLServicesSoap)(this)).TPLinkStokAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bogazici_service.CreateOrderResponse bogazici_service.BBXMLServicesSoap.CreateOrder(bogazici_service.CreateOrderRequest request)
        {
            return base.Channel.CreateOrder(request);
        }
        
        public bogazici_service.Donus CreateOrder(string BayiKodu, string EPosta, string Sifre, string MusteriSiparisNo, string SiparisAciklama, string SevkiyatKod, bogazici_service.Satir[] Satirs)
        {
            bogazici_service.CreateOrderRequest inValue = new bogazici_service.CreateOrderRequest();
            inValue.Body = new bogazici_service.CreateOrderRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            inValue.Body.MusteriSiparisNo = MusteriSiparisNo;
            inValue.Body.SiparisAciklama = SiparisAciklama;
            inValue.Body.SevkiyatKod = SevkiyatKod;
            inValue.Body.Satirs = Satirs;
            bogazici_service.CreateOrderResponse retVal = ((bogazici_service.BBXMLServicesSoap)(this)).CreateOrder(inValue);
            return retVal.Body.CreateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bogazici_service.CreateOrderResponse> bogazici_service.BBXMLServicesSoap.CreateOrderAsync(bogazici_service.CreateOrderRequest request)
        {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<bogazici_service.CreateOrderResponse> CreateOrderAsync(string BayiKodu, string EPosta, string Sifre, string MusteriSiparisNo, string SiparisAciklama, string SevkiyatKod, bogazici_service.Satir[] Satirs)
        {
            bogazici_service.CreateOrderRequest inValue = new bogazici_service.CreateOrderRequest();
            inValue.Body = new bogazici_service.CreateOrderRequestBody();
            inValue.Body.BayiKodu = BayiKodu;
            inValue.Body.EPosta = EPosta;
            inValue.Body.Sifre = Sifre;
            inValue.Body.MusteriSiparisNo = MusteriSiparisNo;
            inValue.Body.SiparisAciklama = SiparisAciklama;
            inValue.Body.SevkiyatKod = SevkiyatKod;
            inValue.Body.Satirs = Satirs;
            return ((bogazici_service.BBXMLServicesSoap)(this)).CreateOrderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BBXMLServicesSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BBXMLServicesSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BBXMLServicesSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://servis.bogazici.com.tr/BBXMLServices.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BBXMLServicesSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://servis.bogazici.com.tr/BBXMLServices.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BBXMLServicesSoap,
            
            BBXMLServicesSoap12,
        }
    }
}
